// 100 extra unique colors with hex codes and names not in the existing database.
import { ColorInfo } from './colorTypes';

export const extraColors: ColorInfo[] = [
  { name: 'Celestial Blue',      hex: '#4997D0', category: 'blue' },
  { name: 'Azure Mist',          hex: '#F0FFFF', category: 'blue' },
  { name: 'Cadmium Green',       hex: '#006B3C', category: 'green' },
  { name: 'Viridian',            hex: '#40826D', category: 'green' },
  { name: 'Kelly Green',         hex: '#339C5E', category: 'green' },
  { name: 'Pistachio',           hex: '#93C572', category: 'green' },
  { name: 'Tea Green',           hex: '#D0F0C0', category: 'green' },
  { name: 'Hunter Green',        hex: '#355E3B', category: 'green' },
  { name: 'Celadon',             hex: '#ACE1AF', category: 'green' },
  { name: 'Shamrock',            hex: '#45CEA2', category: 'green' },
  { name: 'Jade',                hex: '#00A86B', category: 'green' },
  { name: 'Fern',                hex: '#71BC78', category: 'green' },
  { name: 'Eucalyptus',          hex: '#5FB69C', category: 'green' },
  { name: 'Myrtle',              hex: '#21421E', category: 'green' },
  { name: 'Saffron',             hex: '#F4C430', category: 'yellow' },
  { name: 'Dandelion',           hex: '#FED85D', category: 'yellow' },
  { name: 'Tuscan',              hex: '#FAD6A5', category: 'yellow' },
  { name: 'Butterscotch',        hex: '#E1AD01', category: 'yellow' },
  { name: 'Maize',               hex: '#FBEC5D', category: 'yellow' },
  { name: 'Sunglow',             hex: '#FFCC33', category: 'yellow' },
  { name: 'Citrine',             hex: '#E4D00A', category: 'yellow' },
  { name: 'Flax',                hex: '#EEDC82', category: 'yellow' },
  { name: 'Harvest Gold',        hex: '#DA9100', category: 'yellow' },
  { name: 'Amber Yellow',        hex: '#FFBF00', category: 'yellow' },
  { name: 'Ochre',               hex: '#CC7722', category: 'orange' },
  { name: 'Papaya',              hex: '#FED8B1', category: 'orange' },
  { name: 'Tiger',               hex: '#FD6A02', category: 'orange' },
  { name: 'Bittersweet',         hex: '#FE6F5E', category: 'orange' },
  { name: 'Cantaloupe',          hex: '#FFA62B', category: 'orange' },
  { name: 'Desert Sand',         hex: '#EDC9AF', category: 'orange' },
  { name: 'Coral Reef',          hex: '#FF7F50', category: 'orange' },
  { name: 'Apricot',             hex: '#FBCEB1', category: 'orange' },
  { name: 'Atomic Tangerine',    hex: '#FF9966', category: 'orange' },
  { name: 'Sunset Orange',       hex: '#FD5E53', category: 'orange' },
  { name: 'Pumpkin Pie',         hex: '#FFA07A', category: 'orange' },
  { name: 'Alizarin',            hex: '#E32636', category: 'red' },
  { name: 'Vermilion',           hex: '#E34234', category: 'red' },
  { name: 'Poppy',               hex: '#DC343B', category: 'red' },
  { name: 'Flame',               hex: '#E25822', category: 'red' },
  { name: 'Berry',               hex: '#8A4B5F', category: 'red' },
  { name: 'Jazzberry Jam',       hex: '#A50B5E', category: 'red' },
  { name: 'Carmine',             hex: '#960018', category: 'red' },
  { name: 'Burgundy',            hex: '#800020', category: 'red' },
  { name: 'Fire Opal',           hex: '#E95C4B', category: 'red' },
  { name: 'Mahogany',            hex: '#C04000', category: 'red' },
  { name: 'Copper Rose',         hex: '#996666', category: 'red' },
  { name: 'Wild Strawberry',     hex: '#FF43A4', category: 'pink' },
  { name: 'Mauvelous',           hex: '#EF98AA', category: 'pink' },
  { name: 'Melon',               hex: '#FDBCB4', category: 'pink' },
  { name: 'Raspberry',           hex: '#E30B5D', category: 'pink' },
  { name: 'Carnation Pink',      hex: '#FFA6C9', category: 'pink' },
  { name: 'Tulip',               hex: '#FF878D', category: 'pink' },
  { name: 'Punch',               hex: '#F25278', category: 'pink' },
  { name: 'Pink Lemonade',       hex: '#FFD1DC', category: 'pink' },
  { name: 'Cotton Candy',        hex: '#FFBCD9', category: 'pink' },
  { name: 'Bubblegum',           hex: '#FFC1CC', category: 'pink' },
  { name: 'Mystic Maroon',       hex: '#AD4379', category: 'purple' },
  { name: 'Fuchsia',             hex: '#FF00FF', category: 'purple' },
  { name: 'Purple Heart',        hex: '#69359C', category: 'purple' },
  { name: 'Eggplant',            hex: '#614051', category: 'purple' },
  { name: 'Heather',             hex: '#B7C3D0', category: 'purple' },
  { name: 'Wisteria',            hex: '#C9A0DC', category: 'purple' },
  { name: 'Haze',                hex: '#E6E6FA', category: 'purple' },
  { name: 'Mimosa',              hex: '#E4B7D4', category: 'purple' },
  { name: 'French Mauve',        hex: '#D473D4', category: 'purple' },
  { name: 'Plum Purple',         hex: '#5946A6', category: 'purple' },
  { name: 'Irish Coffee',        hex: '#6C4F3D', category: 'brown' },
  { name: 'Coffee',              hex: '#6F4E37', category: 'brown' },
  { name: 'Taupe',               hex: '#483C32', category: 'brown' },
  { name: 'Walnut',              hex: '#773F1A', category: 'brown' },
  { name: 'Hazel',               hex: '#BB8E34', category: 'brown' },
  { name: 'Cocoa',               hex: '#D2691E', category: 'brown' },
  { name: 'Pecan',               hex: '#C39B77', category: 'brown' },
  { name: 'Tan',                 hex: '#D2B48C', category: 'brown' },
  { name: 'Almond',              hex: '#EFDECD', category: 'brown' },
  { name: 'Sand Dune',           hex: '#967117', category: 'brown' },
  { name: 'Linen',               hex: '#FAF0E6', category: 'white' },
  { name: 'Bone',                hex: '#E3DAC9', category: 'white' },
  { name: 'Isabelline',          hex: '#F4F0EC', category: 'white' },
  { name: 'Eggshell',            hex: '#F0EAD6', category: 'white' },
  { name: 'Magnolia',            hex: '#F8F4FF', category: 'white' },
  { name: 'Frost',               hex: '#E5FFF9', category: 'white' },
  { name: 'Smoke',               hex: '#F5F3F0', category: 'white' },
  { name: 'Platinum',            hex: '#E5E4E2', category: 'white' },
  { name: 'Opal',                hex: '#A8C3BC', category: 'white' },
  { name: 'Silver',              hex: '#C0C0C0', category: 'white' },
  { name: 'Dove Gray',           hex: '#D6D6D6', category: 'white' },
  { name: 'Ash Gray',            hex: '#B2BEB5', category: 'white' },
  { name: 'Slate',               hex: '#708090', category: 'blue' },
  { name: 'Cobalt',              hex: '#3D59AB', category: 'blue' },
  { name: 'Lake Blue',           hex: '#7BC8F6', category: 'blue' },
  { name: 'Pacific Blue',        hex: '#1CA9C9', category: 'blue' },
  { name: 'Denim',               hex: '#1560BD', category: 'blue' },
  { name: 'Space Cadet',         hex: '#1D2951', category: 'blue' },
  { name: 'Steel',               hex: '#4682B4', category: 'blue' },
  { name: 'Independence',        hex: '#4C516D', category: 'blue' },
  { name: 'Oxford Blue',         hex: '#002147', category: 'blue' },
  { name: 'Charcoal',            hex: '#36454F', category: 'black' },
  { name: 'Ebony',               hex: '#555D50', category: 'black' },
  { name: 'Ash',                 hex: '#666362', category: 'black' },
  { name: 'Pewter',              hex: '#899499', category: 'black' },
  { name: 'Shadow',              hex: '#8A795D', category: 'black' }
];
